# Generated by Django 4.2.5 on 2023-09-19 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.FloatField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("D", "Deposit"),
                            ("W", "Withdrawal"),
                            ("T", "Transfer"),
                        ],
                        default="T",
                        max_length=1,
                    ),
                ),
                (
                    "payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.customer"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=15)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("S", "Savings"),
                            ("C", "Current"),
                            ("F", "Fixed"),
                            ("R", "Recurring"),
                        ],
                        default="S",
                        max_length=1,
                    ),
                ),
                ("balance", models.FloatField()),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.customer"
                    ),
                ),
            ],
        ),
    ]
